appName: CovidCaseTracker

inputs:
  covid:
    azure:
      storageType: AzureBlobStorage
      containerName: public
      storageAccountName: pandemicdatalake
      blob_sas_token: ""
      blob_relative_path: curated/covid-19/ecdc_cases/latest/ecdc_cases.csv
      format: csv
      options:
        quoteAll: false

transformations:
  - config/covid_tracking_transformations.yaml

output:
  file:
    dir: gs://<BUCKET_NAME>
  azure:
    connectionUrl: jdbc:sqlserver://dataflowazuresqlserver.database.windows.net:1433;database=dataflowazuresqldatabase;trustServerCertificate=true;
    user: 4dm1n157r470r
    password: 4-v3ry-53cr37-p455w0rd
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  aws:
    connectionUrl: jdbc:redshift://dataflow-redshift-cluster.ce0s1cnqwquk.us-east-2.redshift.amazonaws.com:5439/dataflow
    user: adm1n157r470r
    password: OdfdPdeanfioefn232dedw
    driver: com.amazon.redshift.jdbc42.Driver
  gcp:
    temporaryGcsBucket: <BUCKET_NAME>

explain: true

logLevel: WARN

showPreviewLines: 5
