appName: KafkaTransactionsApp

inputs:
  transactions:
    kafka:
      config: /home/bladeaico/.confluent/kafka_cloud.config
      topic: transactions
      consumerGroup: kafkaAppConsumerGroup
      options:
        startingOffsets: earliest
        failOnDataLoss: true
      schemaRegistryUrl: https://psrc-lgy7n.europe-west3.gcp.confluent.cloud

transformations:
  - /config/kafka_transformations.yaml

output:
  gcp:
    temporaryGcsBucket: tmpdataflowbucketkafka
  jdbc:
    connectionUrl: jdbc:sqlserver://dataflowazuresql.database.windows.net:1433;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=60;
    user: dataflow_azureuser
    password: 789ZSVC4fvMs
    dbName: dataflow
    driver: test
streaming:
  triggerMode: Once
  outputMode: append
  checkpointLocation: gs://tmpdataflowbucketkafka/checkpoint/
  batchMode: true
  format: bigquery

explain: true
logLevel: INFO