steps:
  - dataFrameName: salesInUS
    sql:
      SELECT *
      FROM sales
      WHERE Country='United States'
  - dataFrameName: salesInUK
    sql:
      SELECT *
      FROM sales
      WHERE Country='United Kingdom'
output:
  - dataFrameName: salesInUS
    outputType: Parquet
    outputOptions:
      saveMode: Overwrite
      path: salesInUS.parquet
      tableName: salesInUSHiveExternal
      protectFromEmptyOutput: true
  - dataFrameName: salesInUK
    outputType: Parquet
    outputOptions:
      saveMode: Overwrite
      path: salesInUK.parquet
      tableName: salesInUKHiveExternal
  - dataFrameName: salesInUS
    outputType: AzureSQL
    outputOptions:
      saveMode: Append
      dbTable: salesInUS
  - dataFrameName: salesInUK
    outputType: AzureSQL
    outputOptions:
      saveMode: Append
      dbTable: salesInUK
  - dataFrameName: salesInUS
    outputType: AWSRedshift
    outputOptions:
      saveMode: Append
      dbTable: salesInUS
  - dataFrameName: salesInUK
    outputType: AWSRedshift
    outputOptions:
      saveMode: Append
      dbTable: salesInUK
  - dataFrameName: salesInUS
    outputType: GCPBigQuery
    outputOptions:
      saveMode: Append
      dbTable: dataflow_hybrid_cloud.salesInUS
  - dataFrameName: salesInUK
    outputType: GCPBigQuery
    outputOptions:
      saveMode: Append
      dbTable: dataflow_hybrid_cloud.salesInUK